---
- name: Install Elasticsearch
  include: install-es-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Elasticsearch
  template: src={{ item.src }} dest={{ item.dest }}
            owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: 'elasticsearch.yml.j2',
        dest: '/etc/elasticsearch/elasticsearch.yml',
        owner: 'root', group: 'elasticsearch', mode: '0750' }
    - { src: 'elasticsearch.j2',
        dest: '/etc/sysconfig/elasticsearch',
        owner: 'root', group: 'root', mode: '0644' }
  notify: restart elasticsearch

- name: Start Elasticsearch
  service: name=elasticsearch state=started enabled=yes

- name: Make sure Elasticsearch is running before proceeding
  wait_for: port={{ es_network_port }} delay=3 timeout=300